/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LensRouteImport } from './routes/lens'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as WhatsappInventoryRouteImport } from './routes/whatsapp-inventory'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AuthenticatedSellerNewRouteImport } from './routes/_authenticated/seller.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LensRoute = LensRouteImport.update({
  id: '/lens',
  path: '/lens',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappInventoryRoute = WhatsappInventoryRouteImport.update({
  id: '/whatsapp-inventory',
  path: '/whatsapp-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellerNewRoute = AuthenticatedSellerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedSellerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/lens': typeof LensRoute
  '/merchant': typeof MerchantRoute
  '/merchants': typeof MerchantsRoute
  '/nearby': typeof NearbyRoute
  '/pricing': typeof PricingRoute
  '/whatsapp-inventory': typeof WhatsappInventoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/seller/new': typeof AuthenticatedSellerNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/lens': typeof LensRoute
  '/merchant': typeof MerchantRoute
  '/merchants': typeof MerchantsRoute
  '/nearby': typeof NearbyRoute
  '/pricing': typeof PricingRoute
  '/whatsapp-inventory': typeof WhatsappInventoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/seller/new': typeof AuthenticatedSellerNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/lens': typeof LensRoute
  '/merchant': typeof MerchantRoute
  '/merchants': typeof MerchantsRoute
  '/nearby': typeof NearbyRoute
  '/pricing': typeof PricingRoute
  '/whatsapp-inventory': typeof WhatsappInventoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/_authenticated/seller/new': typeof AuthenticatedSellerNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/discover'
    | '/faq'
    | '/lens'
    | '/merchant'
    | '/merchants'
    | '/nearby'
    | '/pricing'
    | '/whatsapp-inventory'
    | '/profile'
    | '/seller'
    | '/product/$id'
    | '/seller/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/discover'
    | '/faq'
    | '/lens'
    | '/merchant'
    | '/merchants'
    | '/nearby'
    | '/pricing'
    | '/whatsapp-inventory'
    | '/profile'
    | '/seller'
    | '/product/$id'
    | '/seller/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/discover'
    | '/faq'
    | '/lens'
    | '/merchant'
    | '/merchants'
    | '/nearby'
    | '/pricing'
    | '/whatsapp-inventory'
    | '/_authenticated/profile'
    | '/_authenticated/seller'
    | '/product/$id'
    | '/_authenticated/seller/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DiscoverRoute: typeof DiscoverRoute
  FaqRoute: typeof FaqRoute
  LensRoute: typeof LensRoute
  MerchantRoute: typeof MerchantRoute
  MerchantsRoute: typeof MerchantsRoute
  NearbyRoute: typeof NearbyRoute
  PricingRoute: typeof PricingRoute
  WhatsappInventoryRoute: typeof WhatsappInventoryRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lens': {
      id: '/lens'
      path: '/lens'
      fullPath: '/lens'
      preLoaderRoute: typeof LensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp-inventory': {
      id: '/whatsapp-inventory'
      path: '/whatsapp-inventory'
      fullPath: '/whatsapp-inventory'
      preLoaderRoute: typeof WhatsappInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seller/new': {
      id: '/_authenticated/seller/new'
      path: '/new'
      fullPath: '/seller/new'
      preLoaderRoute: typeof AuthenticatedSellerNewRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
  }
}

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerNewRoute: typeof AuthenticatedSellerNewRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerNewRoute: AuthenticatedSellerNewRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DiscoverRoute: DiscoverRoute,
  FaqRoute: FaqRoute,
  LensRoute: LensRoute,
  MerchantRoute: MerchantRoute,
  MerchantsRoute: MerchantsRoute,
  NearbyRoute: NearbyRoute,
  PricingRoute: PricingRoute,
  WhatsappInventoryRoute: WhatsappInventoryRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
